spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9090/realms/mycompany-microservices-realm
          jwk-set-uri: http://localhost:9090/realms/mycompany-microservices-realm/protocol/openid-connect/certs
    client:
      keycloak:
        realm: mycompany-microservices-realm
  cloud:
    gateway:
      routes:
        - id: crud
          uri: lb://crud
          predicates:
            - Path=/crud/**
          filters:
            - StripPrefix=1
server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG